class KpPage:
    input = "//input[contains(@aria-label, 'keywords')]"
    pretraga_dugme = "(//span[contains(@class, 'Button_children__3mYJw')])[2]"
    sortiraj = "(//span[contains(@class, 'Button_children__3mYJw')])[8]"
    jeftiniji = "(//button[contains(@class, 'Button_base__Pz8U1 Button_big__6JOpp Sort_orderItem__w4bup')])[1]"
    cena1 = "(//div[contains(@class, 'AdItem_price__jUgxi')])[1]"
    cena2 = "(//div[contains(@class, 'AdItem_price__jUgxi')])[2]"
    euro = "//input[contains(@id, 'amount')]"
    course = "(//div[contains(@class, 'CurrencyConverter_rate__bMsx8')])[2]"
    eur = "CurrencyConverter_convertedAmount__ny2Ny"
    monitor = "//input[contains(@aria-label, 'keywords')]"
    filterZaCenu="(//span[contains(@class, 'SearchTag_priceTagText__VLQ3h')])"
    cenaod="//input[contains(@aria-label, 'priceFrom')]"
    cenado = "//input[contains(@aria-label, 'priceTo')]"
    primenifiltere = "(//button[contains(@class, 'Button_base__Pz8U1 Button_big__6JOpp ButtonPrimaryBlue_primaryBlue__Uz5k1')])[2]"
    cenaprvog = "(//div[contains(@class, 'AdItem_price__jUgxi')])[1]"
    #filterzacenu= "<li class="SearchTagContainer_tagItem___hXdd"
    polisa = "//a[contains(@aria-label, 'Polisa o poštovanju privatnosti')]"
    a = "(//a[contains(@class, 'Link_link__J4Qd8 Button_base__Pz8U1 Button_inherit___tUxa Button_noPadding__JQU_i CategoryHeadlineItem_itemOutter__g9aGN')])[2]"
    ulogujse = "//button[contains(@class, 'Button_base__Pz8U1 Button_big__6JOpp ButtonPrimaryBlue_primaryBlue__Uz5k1 MyKpMenu_loginButton__BGK_f')]"
    facebook = "(//span[contains(@class, 'Button_children__3mYJw')])[22]"
    usluge = "(//a[contains(@class, 'Link_link__J4Qd8 Link_inherit___qXEP Tabs_tabListItem__Ym4wo')])[2]"
    usluge_auto_moto = "//a[contains(@href, '/usluge-auto-moto/kategorija/1410')]"
    kupujemprodajem =" (//a[contains(@class, 'Link_link__J4Qd8 Logo_logo__2vSTN')])[1]"
